[env:xplained328P]
platform = atmelavr
board = ATmega328P

board_build.mcu = atmega328p
board_build.f_cpu = 16000000UL

upload_protocol = custom
upload_command = "C:\Users\Madalin\AppData\Local\Arduino15\packages\MiniCore\tools\avrdude\8.0-arduino.1\bin\avrdude.exe" "-CC:\Users\Madalin\AppData\Local\Arduino15\packages\MiniCore\tools\avrdude\8.0-arduino.1\etc\avrdude.conf" -v -V -patmega328p -cxplainedmini -Uflash:w:$SOURCE:i

build_flags =
    -std=gnu99
    -Os
    -Wall